[verilog]
# Include all SystemVerilog files recursively from your source folders
include = [
    "processor/**/*.sv",
    # Add other folders with SV files here if needed, e.g.:
    # "rtl/**/*.sv",
    # "modules/**/*.sv",
]

# No defines needed since you didn't mention any macros

# Exclude your Python testbench folders so SVLS doesn't scan those
exclude = [
    "processor/sim/",
]

[option]
linter = false
