name: CocoTB Design Verification
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ENV
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - name: Install Deps
        run: |
          python -m pip install --upgrade pip
          pip install cocotb
      - name: Run Pytest
        run: pytest

