name: CocoTB Design Verification
on: [push]

jobs:
  TestDesign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ENV
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - name: Install Python Deps
        run: |
          python -m pip install --upgrade pip
          pip install cocotb pytest
      - name: Install iverilog/icarus
          sudo apt-get update
          sudo apt-get install -y iverilog
      - name: Run Pytest
        run: pytest
        continue-on-error: true

